---
# handlers file for application-deploy

- name: restart supervisorctl
  service: name=supervisor state=restarted

- name: reload supervisorctl
  service: name=supervisor state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

- name: restart demo-a-b
  shell: "/usr/bin/supervisorctl restart demo-a-b"

- name: haproxy-restart
  service: name=haproxy state=restarted
