---

- name: install nginx
  apt: name=nginx state=installed

- name: global configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: nginx.conf, dest: /etc/nginx/nginx.conf }
  notify:
    - nginx-restart
